### PR TITLE
closes #86

### LINKED ISSUE #86: Unlock Vaults located on Read-Only Storages
Currently, vaults which are located on Read-Only-Storages cannot be opened and if one attempts to do it, the following exception is thrown:
```
java.io.IOException: Error during file system creation.
	at org.cryptomator.cryptofs.CryptoFileSystems.create(CryptoFileSystems.java:53)
	at org.cryptomator.cryptofs.CryptoFileSystemProvider.newFileSystem(CryptoFileSystemProvider.java:302)
	at org.cryptomator.cryptofs.CryptoFileSystemProvider.newFileSystem(CryptoFileSystemProvider.java:94)
	at java.base/java.nio.file.FileSystems.newFileSystem(Unknown Source)
	at java.base/java.nio.file.FileSystems.newFileSystem(Unknown Source)
	at org.cryptomator.cryptofs.CryptoFileSystemProvider.newFileSystem(CryptoFileSystemProvider.java:135)
Caused by: java.io.UncheckedIOException: java.nio.file.AccessDeniedException: [REDACTED]\masterkey.cryptomator.ABEFFC47.bkup
	at org.cryptomator.cryptofs.CryptoFileSystemModule.provideCryptor(CryptoFileSystemModule.java:42)
	at org.cryptomator.cryptofs.CryptoFileSystemModule_ProvideCryptorFactory.provideCryptor(CryptoFileSystemModule_ProvideCryptorFactory.java:56)
	at org.cryptomator.cryptofs.CryptoFileSystemModule_ProvideCryptorFactory.get(CryptoFileSystemModule_ProvideCryptorFactory.java:43)
	at org.cryptomator.cryptofs.CryptoFileSystemModule_ProvideCryptorFactory.get(CryptoFileSystemModule_ProvideCryptorFactory.java:11)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at org.cryptomator.cryptofs.CryptoFileSystemImpl_Factory.get(CryptoFileSystemImpl_Factory.java:110)
	at org.cryptomator.cryptofs.CryptoFileSystemImpl_Factory.get(CryptoFileSystemImpl_Factory.java:16)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at org.cryptomator.cryptofs.DaggerCryptoFileSystemProviderComponent$CryptoFileSystemComponentImpl.cryptoFileSystem(DaggerCryptoFileSystemProviderComponent.java:325)
	at org.cryptomator.cryptofs.CryptoFileSystems.lambda$create$0(CryptoFileSystems.java:47)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(Unknown Source)
	at org.cryptomator.cryptofs.CryptoFileSystems.create(CryptoFileSystems.java:40)
	... 19 more
Caused by: java.nio.file.AccessDeniedException: [REDACTED]\masterkey.cryptomator.ABEFFC47.bkup
	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileCopy.copy(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.copy(Unknown Source)
	at java.base/java.nio.file.Files.copy(Unknown Source)
	at org.cryptomator.cryptofs.CryptoFileSystemModule.backupMasterkeyFileIfRequired(CryptoFileSystemModule.java:48)
	at org.cryptomator.cryptofs.CryptoFileSystemModule.provideCryptor(CryptoFileSystemModule.java:39)
	... 30 more
```

This comes from the fact, that every time a vault is sucessfully unlocked, a backup of the masterkey file is written to the another file. The target file has always the same name, therefore this fails on Read-Only-Storages.

A suggestion made by @overheadhunter : For read-only drives, one could do a bitwise comparison of the existing backup file and the one to be created. If they match, don't write.

### PR DESCRIPTION
**Pull request by infeo**
This implements the suggestion mentioned in the issue description of :

https://github.com/cryptomator/cryptofs/issues/86

### CODE REVIEW

**Comment by infeo** [comment]
>Instead of doing a "let's make it work somehow" fix, we should do a proper refactoring of the backupMasterkeyFileIfRequired method (making the ifRequired part more intelligent).

I second that. But before change the method: Is the word _required_ correct in the method name? From my perspective "possible" or "desired" would be actual term, since we are always making a backup except the filesystem is unlocked in read-only mode, or am I wrong?

> Second, and more severe: This doesn't solve the issue under all circumstances. If there isn't a bkup file in the first place (never created due to readonly), Files.readAllBytes will fail with an IOException.

That is... true. This introduces even new errors 😓 I'll refactor it.

**Comment by overheadhunter** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/org/cryptomator/cryptofs/CryptoFileSystemModule.java  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/cryptomator/cryptofs/pullRequest?prid=5660078&bid=18528341)

**Comment by infeo** [comment]
I refactored it into one method.

As written in the commit message, only valid states are now:
* vault is opened read-only
* storage device is writeable
* storage device is read-only, backup file exists and content match with master key

Otherwise an IllegalStateException is thrown.

Tests are missing, but if someone points me to the correct place, i'll implement them.

**Comment by overheadhunter** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/org/cryptomator/cryptofs/CryptoFileSystemModule.java  1
- src/main/java/org/cryptomator/cryptofs/common/MasterkeyBackupHelper.java  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/cryptomator/cryptofs/pullRequest?prid=5660078&bid=18528341)

**Pull request merged**
